name: YouTube→Sheet自動実行

# 手動実行だけ利用する場合
on:
  workflow_dispatch: {}

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリをチェックアウト
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      # 2. Python 環境をセットアップ
      - name: Python セットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 3. 必要ライブラリをインストール
      - name: 依存ライブラリをインストール
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. GitHub Secrets を使って credentials.json を生成
      - name: credentials.json を復元
        run: |
          echo "${{ secrets.GCP_CREDENTIALS_JSON }}" > credentials.json

      # 5. その他の Secrets を環境変数に設定
      - name: 環境変数設定（YouTube API キー, スプレッドシートID）
        run: |
          echo "YOUTUBE_API_KEYS=${{ secrets.YOUTUBE_API_KEYS }}" >> $GITHUB_ENV
          echo "SHEET_ID=${{ secrets.SHEET_ID }}" >> $GITHUB_ENV

      # 6. 全チャンネル分のスクリプトを実行
      - name: 全チャンネル分を実行
        run: |
          python run_all.py
